---
# This playbook performs service cleanup
#

- hosts: localhost
  connection: local
  vars_files:
    - keys.yml
  tasks:
    - include: roles/openstack_infra/tasks/cleanup.yml
    - include: roles/galaxy/remove-requirements.yml
